/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.chitiethoadon.ChiTietHoaDonDAO;
import dao.hoadon.HoaDonDAO;
import dao.khachhang.KhachHangDAO;
import dao.sanpham.SanPhamDAO;
import entity.ChiTietHoaDon;
import entity.DateTimeHD;
import entity.HoaDon;
import entity.KhachHang;
import entity.AccountSession;
import entity.SanPham;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ĐỨC DUY
 */
public class BanHangScreen extends javax.swing.JFrame {

    ChiTietHoaDonDAO chitietdao = new ChiTietHoaDonDAO();
    AccountSession lb = new AccountSession();
    DateTimeHD dateTimeHD = new DateTimeHD();
    private ArrayList<String> listsanpham = new ArrayList<>();

    private ArrayList<String> listkhachhang = new ArrayList<>();

    // đầu tiên phải tạo 1 row có sẵn ngoài contructor để nó lưu biến row , số 8 bên trong tương đương với số cột;
    Object[] row = new Object[8];

    // tạo 1 biến defaultablemodel là thuộc tính chứa các row và cột 
    DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form BanHangScreen
     */
    public BanHangScreen() {
        initComponents();
        txtTenNV.setText(lb.getTaikhoan());
        txtMaKH.setText("3");
        txtTenKH.setText("GUEST");
        txtSdtKH.setText("Khong Co");
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension d = tk.getScreenSize();
        int sw = (int) d.getWidth();
        int sh = (int) d.getHeight();
        int fw = this.getWidth();
        int fh = this.getHeight();
        int xpos = (sw - fw) / 2;
        int ypos = (sh - fh) / 2;
        this.setLocation(xpos, ypos);

        listsanpham = new SanPhamDAO().getlist();

        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        Date date = new Date();
        txtThoiGian.setText(format.format(date));
        //luu thoi gian tao hoa don
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        dateTimeHD.setTime(dateFormat.format(date));

        // tạo 1 mảng 1 chiều chứa các tên cột có trong jtable đó
        String[] cot = {"STT", "Mã hàng", "Tên hàng", "Số lượng", "Đơn giá", "Thành tiền ", "Chiết khấu ", "Thanh toán"};
        listkhachhang = new KhachHangDAO().listkhachang();

        // add tên các cột vào trong model 
        model.setColumnIdentifiers(cot);

        tblDanhSach.setModel(model);

        tblDanhSach.setRowHeight(30);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtThoiGian = new javax.swing.JTextField();
        txtTenNV = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnDangXuat = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtSoluong = new javax.swing.JTextField();
        txtTienNhan = new javax.swing.JTextField();
        txtThanhTien = new javax.swing.JTextField();
        txtTienThua = new javax.swing.JTextField();
        txtMaKH = new javax.swing.JTextField();
        txtTenKH = new javax.swing.JTextField();
        txtSdtKH = new javax.swing.JTextField();
        txtMaSanPham = new javax.swing.JTextField();
        txtTenSanPham = new javax.swing.JTextField();
        txtSoLuongSP = new javax.swing.JTextField();
        txtChietKhau = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        btnThemVaoHoaDon = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();
        btnUpdateHD = new javax.swing.JButton();
        btnTaoHDMoi = new javax.swing.JButton();
        btnLuuHoaDon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cashier.png"))); // NOI18N
        jLabel3.setText("BÁN HÀNG");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Thời gian");

        txtThoiGian.setEditable(false);
        txtThoiGian.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtThoiGian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThoiGianActionPerformed(evt);
            }
        });

        txtTenNV.setEditable(false);
        txtTenNV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nhân viên");

        btnDangXuat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logOut.png"))); // NOI18N
        btnDangXuat.setText("ĐĂNG XUẤT");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addComponent(btnDangXuat)
                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(btnDangXuat)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 153));
        jLabel4.setText("TỔNG HỢP THANH TOÁN");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Số Lượng Hàng");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Thành Tiền");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Tiền nhận");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Tiền thừa");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 153));
        jLabel18.setText("THÔNG TIN KHÁCH HÀNG");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Mã KH");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Tên KH");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("SĐT");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Mã hàng");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText("Tên hàng");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("Số lượng");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("Chiết khấu");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("Đơn giá");

        txtSoluong.setEditable(false);

        txtTienNhan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTienNhanKeyPressed(evt);
            }
        });

        txtThanhTien.setEditable(false);

        txtTienThua.setEditable(false);

        txtMaKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaKHKeyPressed(evt);
            }
        });

        txtTenKH.setEditable(false);

        txtSdtKH.setEditable(false);

        txtMaSanPham.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaSanPhamKeyPressed(evt);
            }
        });

        txtTenSanPham.setEditable(false);

        txtChietKhau.setEditable(false);

        txtDonGia.setEditable(false);

        btnThemVaoHoaDon.setText("Thêm vào hóa đơn");
        btnThemVaoHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemVaoHoaDonActionPerformed(evt);
            }
        });

        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSach);

        btnUpdateHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/updateICON.png"))); // NOI18N
        btnUpdateHD.setText("Cập nhật hóa đơn");
        btnUpdateHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateHDActionPerformed(evt);
            }
        });

        btnTaoHDMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/addNewBill.png"))); // NOI18N
        btnTaoHDMoi.setText("Tạo hóa đơn mới");
        btnTaoHDMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoHDMoiActionPerformed(evt);
            }
        });

        btnLuuHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bill.png"))); // NOI18N
        btnLuuHoaDon.setText("Lập hóa đơn");
        btnLuuHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuHoaDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTienNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(8, 8, 8))
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtSoluong)
                                .addComponent(txtThanhTien)))
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSdtKH, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(27, 27, 27)
                                .addComponent(txtTenSanPham))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(32, 32, 32)
                                .addComponent(txtMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSoLuongSP, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtChietKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnThemVaoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLuuHoaDon)
                .addGap(69, 69, 69)
                .addComponent(btnUpdateHD)
                .addGap(48, 48, 48)
                .addComponent(btnTaoHDMoi)
                .addGap(286, 286, 286))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(txtMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuongSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(txtChietKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThemVaoHoaDon))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtTienNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtSdtKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTaoHDMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuuHoaDon)
                    .addComponent(btnUpdateHD))
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtThoiGianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThoiGianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThoiGianActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        DangNhapScreen dangNhapScreen = new DangNhapScreen();
        dangNhapScreen.setVisible(true);
        dangNhapScreen.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        dispose();

    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void txtMaKHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaKHKeyPressed
        // TODO add your handling code here:
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_BACK_SPACE:
                break;
            case KeyEvent.VK_ENTER:
                txtMaKH.setText(txtMaKH.getText());
                String makh = txtMaKH.getText();
                KhachHangDAO khd = new KhachHangDAO();

                try {
                    KhachHang kh = khd.getId(makh);
                    txtTenKH.setText(kh.getTenkh());
                    txtSdtKH.setText(kh.getSdt());

                } catch (SQLException ex) {
                    Logger.getLogger(BanHangScreen.class.getName()).log(Level.SEVERE, null, ex);
                }

                break;
            default:
                EventQueue.invokeLater(new Runnable() {

                    @Override
                    public void run() {
                        String text = txtMaKH.getText();
                        timkiemkhachhang(text);
                    }
                });
        }
    }//GEN-LAST:event_txtMaKHKeyPressed

    private void txtTienNhanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienNhanKeyPressed
        // TODO add your handling code here:
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_BACK_SPACE:
                break;
            case KeyEvent.VK_ENTER:
                double tiennhan = Double.parseDouble(txtTienNhan.getText());
                double thanhtien = Double.parseDouble(txtThanhTien.getText());

                double tienthua = tiennhan - thanhtien;
                txtTienThua.setText(String.valueOf(tienthua));
                break;
            default:
                break;
        }
    }//GEN-LAST:event_txtTienNhanKeyPressed

    private void btnLuuHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuHoaDonActionPerformed
        // TODO add your handling code here:
        int sohang = model.getRowCount();
        txtSoluong.setText(String.valueOf(sohang));
        double thanhtien = 0;
        for (int i = 0; i < sohang; i++) {
            thanhtien += Double.parseDouble(model.getValueAt(i, 7).toString());

        }

        txtThanhTien.setText(String.valueOf(thanhtien));
    }//GEN-LAST:event_btnLuuHoaDonActionPerformed

    private void btnThemVaoHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemVaoHoaDonActionPerformed
        // TODO add your handling code here:

        int soluong = tblDanhSach.getRowCount() + 1;

        txtSoluong.setText(String.valueOf(soluong));

        double dongia = Double.parseDouble(txtDonGia.getText());

        int soluongban = Integer.parseInt(txtSoLuongSP.getText());

        double thanhtien = soluongban * dongia;

        double chietkhau = Double.parseDouble(txtChietKhau.getText());
        double thanhtoan = thanhtien - (thanhtien * chietkhau / 100);
        String thanhtoantext = String.valueOf(thanhtoan);
        String thanhtientext = String.valueOf(thanhtien);
        String soluongtext = String.valueOf(soluong);
        row[0] = soluongtext;
        row[1] = txtMaSanPham.getText();
        row[2] = txtTenSanPham.getText();
        row[3] = txtSoLuongSP.getText();
        row[4] = txtDonGia.getText();
        row[5] = thanhtien;
        row[6] = txtChietKhau.getText();
        row[7] = thanhtoan;

        AccountSession lb = new AccountSession();
        int mnv = lb.getManv();

        String dateHD = dateTimeHD.getTime();
        HoaDon hd = new HoaDon(0, Integer.parseInt(txtMaKH.getText()), dateHD, mnv);
        HoaDonDAO hdd = new HoaDonDAO();

        // ddaay laf them cac thuộc tính trên vào trong database;
        boolean ketqua = hdd.insertHoaDon(hd);
        if (ketqua == true) {

            HoaDon hoadon = hdd.gethoadon(Integer.parseInt(txtMaKH.getText()), dateHD, mnv);
            ChiTietHoaDon cthd = new ChiTietHoaDon(hoadon.getMahd(), Integer.parseInt(txtMaSanPham.getText()), Integer.parseInt(txtSoLuongSP.getText()));
            ChiTietHoaDonDAO chitietdao = new ChiTietHoaDonDAO();

            boolean ketqua2 = chitietdao.insert(cthd);
            if (ketqua2 == true) {
                //JOptionPane.showMessageDialog(rootPane, "them hoa don thanh cong");
                txtMaSanPham.setText("");
                txtTenSanPham.setText("");
                txtSoLuongSP.setText("");
                txtDonGia.setText("");
                txtChietKhau.setText("");

                // them hang vao trong model 
                model.addRow(row);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Số lượng hàng trong kho không đủ");
            }

        }
    }//GEN-LAST:event_btnThemVaoHoaDonActionPerformed

    private void txtMaSanPhamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaSanPhamKeyPressed
        // TODO add your handling code here:
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_BACK_SPACE:
                break;
            case KeyEvent.VK_ENTER:
                txtMaSanPham.setText(txtMaSanPham.getText());
                int masanpham = Integer.parseInt(txtMaSanPham.getText());
                SanPhamDAO spd = new SanPhamDAO();

                try {
                    SanPham sp = spd.findById(masanpham);
                    txtTenSanPham.setText(sp.getTensp());
                    txtDonGia.setText(String.valueOf(sp.getDongia()));
                    txtChietKhau.setText(String.valueOf(sp.getChietkhau()));
                } catch (SQLException ex) {
                    Logger.getLogger(BanHangScreen.class.getName()).log(Level.SEVERE, null, ex);
                }

                break;
            default:
                EventQueue.invokeLater(new Runnable() {

                    @Override
                    public void run() {
                        String text = txtMaSanPham.getText();
                        timkiem(text);
                    }
                });
        }
    }//GEN-LAST:event_txtMaSanPhamKeyPressed

    private void btnTaoHDMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoHDMoiActionPerformed
        // TODO add your handling code here:
        txtTenNV.setText(lb.getTaikhoan());
        txtMaKH.setText("3");
        txtTenKH.setText("GUEST");
        txtSdtKH.setText("Khong Co");
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        Date date = new Date();
        txtThoiGian.setText(format.format(date));

        txtChietKhau.setText("");
        txtDonGia.setText("");
        txtMaSanPham.setText("");

        txtTenSanPham.setText("");
        txtMaKH.setText("");
        txtTenKH.setText("");
        txtSdtKH.setText("");

        txtThanhTien.setText("");
        txtTienNhan.setText("");
        txtTienThua.setText("");

        txtSoLuongSP.setText("");
        txtSoluong.setText("");
        String[] cot = {"STT", "Mã hàng", "Tên hàng", "Số lượng", "Đơn giá", "Thành tiền ", "Chiết khấu ", "Thanh toán"};
//        row[0] = "";
//        row[1] = "";
//        row[2] = "";
//        row[3] = "";
//        row[4] = "";
//        row[5] = "";
//        row[6] = "";
//        row[7] = "";
//
//        model.setColumnIdentifiers(cot);
//        model.addRow(row);
        for (int i = model.getRowCount() - 1; i >= 0; i--) {
            model.removeRow(i);

        }

        model.setColumnIdentifiers(cot);
        tblDanhSach.setModel(model);
    }//GEN-LAST:event_btnTaoHDMoiActionPerformed

    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMouseClicked
        // TODO add your handling code here:
        String[] cot = {"STT", "Mã hàng", "Tên hàng", "Số lượng", "Đơn giá", "Thành tiền ", "Chiết khấu ", "Thanh toán"};
        int row = tblDanhSach.getSelectedRow();

        txtMaSanPham.setText(String.valueOf(model.getValueAt(row, 1)));
        txtTenSanPham.setText(String.valueOf(model.getValueAt(row, 2)));
        txtSoLuongSP.setText(String.valueOf(model.getValueAt(row, 3)));
        txtDonGia.setText(String.valueOf(model.getValueAt(row, 4)));
        txtChietKhau.setText(String.valueOf(model.getValueAt(row, 6)));

    }//GEN-LAST:event_tblDanhSachMouseClicked

    private void btnUpdateHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateHDActionPerformed
        // TODO add your handling code here:
        AccountSession lb = new AccountSession();
        int mnv = lb.getManv();

        String dateHD = dateTimeHD.getTime();
//        HoaDon hd = new HoaDon(0, Integer.parseInt(txtMaKH.getText()), dateHD, mnv);
        HoaDonDAO hoaDonDAO = new HoaDonDAO();

        // ddaay laf them cac thuộc tính trên vào trong database;
//        boolean ketqua = hoaDonDAO.updateHoaDon(hd);
//        if (ketqua == true) {

            HoaDon hoadon = hoaDonDAO.gethoadon(Integer.parseInt(txtMaKH.getText()), dateHD, mnv);

            //lay ra chi tiet hoa don cu
            ChiTietHoaDon hdCu = chitietdao.getChiTietHoaDon(hoadon.getMahd());
            int soluongBanCu = hdCu.getSoluongban();
            //tao chi tiet hoa don moi
            ChiTietHoaDon cthd = new ChiTietHoaDon();
            cthd = new ChiTietHoaDon(hoadon.getMahd(), Integer.parseInt(txtMaSanPham.getText()), Integer.parseInt(txtSoLuongSP.getText()));

            boolean ketqua2 = chitietdao.update(cthd, soluongBanCu);
            
            
            //lay ra dong dang chon
            int row=tblDanhSach.getSelectedRow();
            
            int soluong = tblDanhSach.getRowCount() + 1;

            txtSoluong.setText(String.valueOf(soluong));

            double dongia = Double.parseDouble(txtDonGia.getText());

            int soluongban = Integer.parseInt(txtSoLuongSP.getText());

            double thanhtien = soluongban * dongia;

            double chietkhau = Double.parseDouble(txtChietKhau.getText());
            double thanhtoan = thanhtien - (thanhtien * chietkhau / 100);
            String thanhtoantext = String.valueOf(thanhtoan);
            String thanhtientext = String.valueOf(thanhtien);
            
            tblDanhSach.setValueAt(txtSoLuongSP.getText(), row, 3);
            tblDanhSach.setValueAt(thanhtientext, row, 5);
            tblDanhSach.setValueAt(thanhtoantext, row, 7);
            if (ketqua2 == true) {
                //JOptionPane.showMessageDialog(rootPane, "them hoa don thanh cong");
                txtMaSanPham.setText("");
                txtTenSanPham.setText("");
                txtSoLuongSP.setText("");
                txtDonGia.setText("");
                txtChietKhau.setText("");

                // them hang vao trong model 
//                model.addRow(row);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Số lượng hàng trong kho không đủ");
            }

        

    }//GEN-LAST:event_btnUpdateHDActionPerformed
    public void timkiem(String text) {
        String giatrithaythe = "";
        int batdau = text.length();

        System.out.println("do dai " + listsanpham.size());
        int ketthuc = text.length();
        for (int i = 0; i < listsanpham.size(); i++) {
            if (listsanpham.get(i).startsWith(text)) {
                giatrithaythe = listsanpham.get(i).toString();
                ketthuc = giatrithaythe.length();

                break;
            }
        }

        if (ketthuc > batdau) {

            txtMaSanPham.setText(giatrithaythe);
            txtMaSanPham.setCaretPosition(ketthuc);
            txtMaSanPham.moveCaretPosition(batdau);

        }

    }

    public void timkiemkhachhang(String text) {
        String giatrithaythe = "";
        int batdau = text.length();

        System.out.println("do dai " + listsanpham.size());
        int ketthuc = text.length();
        for (int i = 0; i < listkhachhang.size(); i++) {
            if (listkhachhang.get(i).startsWith(text)) {
                giatrithaythe = listkhachhang.get(i).toString();
                ketthuc = giatrithaythe.length();

                break;
            }
        }

        if (ketthuc > batdau) {

            txtMaKH.setText(giatrithaythe);
            txtMaKH.setCaretPosition(ketthuc);
            txtMaKH.moveCaretPosition(batdau);

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BanHangScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BanHangScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BanHangScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BanHangScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BanHangScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnLuuHoaDon;
    private javax.swing.JButton btnTaoHDMoi;
    private javax.swing.JButton btnThemVaoHoaDon;
    private javax.swing.JButton btnUpdateHD;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDanhSach;
    private javax.swing.JTextField txtChietKhau;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtMaSanPham;
    private javax.swing.JTextField txtSdtKH;
    private javax.swing.JTextField txtSoLuongSP;
    private javax.swing.JTextField txtSoluong;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtTenSanPham;
    private javax.swing.JTextField txtThanhTien;
    private javax.swing.JTextField txtThoiGian;
    private javax.swing.JTextField txtTienNhan;
    private javax.swing.JTextField txtTienThua;
    // End of variables declaration//GEN-END:variables
}
